#!/bin/bash

echo "UM: Loaded main script. Starting..."

function err_exit() {
    echo "Installation failed. Please try again."
    exit 1
}
trap "err_exit" ERR

export DEBIAN_FRONTEND=noninteractive

read -r -p "UM: Install Homebrew? [Y/n] " hb
case $hb in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install wget? [Y/n] " wg
case $wg in
    [yY][eE][sS]|[yY])
        echo "UM: Installing wget..."
        brew install wget
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install Node.js? [Y/n] " nj
case $nj in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Node.js..."
        brew install node
        brew install npm
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

echo "UM has finished! Enjoy your new software!"
