#!/bin/bash
# UM Utility 1.3.2

echo "UM: Loaded main script. Starting..."

function err_exit() {
    echo "Installation failed. Please try again."
    exit 1
}
trap "err_exit" ERR

export DEBIAN_FRONTEND=noninteractive

read -r -p "UM: Install Homebrew? [Y/n] " hb
case $hb in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install Microsoft Edge? [Y/n] " me
case $me in
    [yY][eE][sS]|[yY])
        echo "UM: Starting UM-pkg agent..."
        echo "UM-pkg: Started agent! Installing..."
        cd /opt
        sudo mkdir um-pkg
        cd um-pkg
        sudo curl -o edge.pkg https://officecdn-microsoft-com.akamaized.net/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/MicrosoftEdge-87.0.664.60.pkg?platform=Mac&Consent=1&channel=Stable
        for f in *.pkg ; 
            do sudo installer -verbose -pkg "$f" -target CurrentUserHomeDirectory
        done
        echo "UM: Closing UM-pkg agent..."
        echo "UM Closed UM-pkg agent!"
        echo "UM: Cleaning up..."
        cd /opt
        sudo rm -rf um-pkg
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install Homebrew Cask? [Y/n] " hbc
case $hbc in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Homebrew Cask..."
        brew install cask
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install Microsoft Powershell (Requires Homebrew, Cask)? [Y/n] " mp
case $mp in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Microsoft Powershell..."
        brew install --cask powershell
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install ClamAV (Requires Homebrew)? [Y/n] " ca
case $ca in
    [yY][eE][sS]|[yY])
        echo "UM: Installing ClamAV..."
        brew install clamav
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install Starboard X? [Y/n] " sx
case $sx in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Starboard X..."
        curl -o sx.zip https://github.com/js3r2/umber-insider/raw/inst-files/sx.zip
        unzip -b sx.zip
        mv Starboard\ X.app /Applications
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install wget? [Y/n] " wg
case $wg in
    [yY][eE][sS]|[yY])
        echo "UM: Installing wget..."
        brew install wget
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

read -r -p "UM: Install Node.js? [Y/n] " nj
case $nj in
    [yY][eE][sS]|[yY])
        echo "UM: Installing Node.js..."
        cd 
        mkdir um-temp
        cd um-temp
        curl -o node.pkg https://nodejs.org/dist/v14.15.2/node-v14.15.2.pkg
        sudo installer -pkg node.pkg -target /
        echo "UM: Node.js: Cleaning up..."
        cd 
        rm -rf um-temp
    ;;
    [nN][oO]|[nN]|'')
        echo "UM: Skipping..."
    ;;
esac

echo "UM has finished! Enjoy your new software!"
